name: Sync Cardinal-Cryptography repo with Aleph-Zero-Foundation repo

on:
  # NOTE: changed to "manual workflow dispatch" for now.
  # TODO: To be automated again, when workflows stabilize
  # and pushes to main origin will be forbidden.
  workflow_dispatch:

#  workflow_run:
#    workflows: ["Autobump version"]
#    branches: [main]
#    types:
#      - completed

jobs:
  sync:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'Cardinal-Cryptography/AlephBFT'}}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: "main"
          token: ${{ secrets.SYNCAZF }}
      - name: Push to Aleph-Zero-Foundation
        run: git push https://x-access-token:${{ secrets.SYNCAZF }}@github.com/aleph-zero-foundation/AlephBFT.git
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: credentials
        uses: actions-rs/cargo@v1
        with:
          command: login
          args: ${{ secrets.CRATES_IO_TOKEN }}
      - name: publish
        run: |
            cargo publish
